# : Manager [[[

[mgr]
cwd = { fg = "#dfe3e7" }

# Tab
tab_active = { fg = "#003549", bg = "#8fcef3", bold = true }
tab_inactive = { fg = "#c3e8ff", bg = "#001e2c" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#9978ff", bg = "#9978ff" }
marker_cut = { fg = "#e6deff", bg = "#e6deff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#cac1ea", bg = "#cac1ea" }

# Count
count_copied = { fg = "#1c1736", bg = "#e6deff" }
count_cut = { fg = "#1c1736", bg = "#e6deff" }
count_selected = { fg = "#003549", bg = "#cac1ea" }

# Border
border_symbol = " "
border_style  = { fg = "#8fcef3" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#003549", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#8fcef3", fg = "#003549", bold = true }
normal_alt  = { bg = "#41484d", fg = "#c0c7cd" }

# Select mode
select_main = { bg = "#b5c9d7", fg = "#20333e", bold = true }
select_alt  = { bg = "#41484d", fg = "#c0c7cd" }

# Unset mode
unset_main = { bg = "#cac1ea", fg = "#322c4c", bold = true }
unset_alt  = { bg = "#41484d", fg = "#c0c7cd" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#8fcef3", bg = "#353a3d" }
progress_error = { fg = "#ffb4ab", bg = "#353a3d" }

# Permissions
permissions_t = { fg = "#55809e" }
permissions_w = { fg = "#684fc3" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#7245ff" }
permissions_s = { fg = "#2aadff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#8fcef3" }
active = { fg = "#cac1ea", bold = true }

# : ]]]


# : Input [[[

[input]
border = { fg = "#8fcef3" }
value = { fg = "#dfe3e7" }

# : ]]]

# : Tabs [[[

[tabs]
active = { fg = "#8fcef3", bold = true, bg = "#0f1417" }
inactive = { fg = "#b5c9d7", bg = "#0f1417" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#8fcef3", bg = "#003549" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#8fcef3" }
title = {}
hovered = { fg = "#e6deff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#353a3d" }
cand = { fg = "#8fcef3" }
rest = { fg = "#003549" }
desc = { fg = "#dfe3e7" }
separator = " ‚ñ∂ "
separator_style = { fg = "#dfe3e7" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#dfe3e7" }
run = { fg = "#dfe3e7" }
footer = { fg = "#20333e", bg = "#b5c9d7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#cac1ea" }
title_warn = { fg = "#8fcef3" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#dfe3e7" },
    { name = "*/", fg = "#8fcef3" },
]

# : ]]]
