[config]


[templates.gtk3]
  input_path = './templates/gtk-colors.css'
  output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.niri]
  input_path  = './templates/niri-colors.kdl'
  output_path = '~/.config/niri/colors.kdl'

[templates.vicinae]
  input_path = '~/.config/matugen/templates/vicinae.toml'
  output_path = '~/.local/share/vicinae/themes/matugen.toml'
  post_hook = 'vicinae theme set matugen'

[templates.hyprlock]
  input_path  = './templates/hyprlock-color.conf'
  output_path = '~/.config/hypr/hyprlock-color.conf'

[templates.starship]
  input_path = './templates/starship-colors.toml'
  output_path = '~/.config/starship/starship.toml'

[templates.kitty]
  input_path  = './templates/kitty-colors.conf'
  output_path = '~/.config/kitty/colors.conf'
  post_hook = 'pkill -SIGUSR1 kitty'

[templates.mako]
  input_path = './templates/mako'
  output_path = '~/.config/mako/config'
  post_hook = 'makoctl reload'

[templates.waybar]
  input_path = './templates/colors.css'
  output_path = '~/.config/waybar/colors.css'

#[templates.yazi]
#  input_path = './templates/yazi-theme.toml'
#  output_path = '~/.config/yazi/theme.toml'
